### ISSUE TITLE
Could not reach any registry endpoint

### ISSUE THREAD

**Issue by rbarrera-ap** [oracle/container-images#10]
I'm trying to pull any of the  oraclelinux images and am getting 'Could not reach any registry endpoint' errors.

[root@SERVER123 ~]# docker pull oraclelinux:6-slim
6-slim: Pulling from oraclelinux
3690474eb5b4: Download complete
cd4582e8e027: Pulling fs layer
cd4582e8e027: Downloading 2.653 MB/43.75 MB
Pulling repository oraclelinux
FATA[0001] Could not reach any registry endpoint

**Comment by Djelibeybi** [comment]
Do you perhaps need to configure a proxy for Docker so it can reach the Docker Hub: https://docs.oracle.com/cd/E52668_01/E87205/html/docker_install_upgrade_proxy.html

**Comment by rbarrera-ap** [comment]
Thank you for your response. I've pulled these images previously without a proxy. Has anything changed within the Docker Hub recently that would require proxy?

**Comment by Djelibeybi** [comment]
Not to my knowledge Can you pull any image or do they all fail with this same error?

**Comment by rbarrera-ap** [comment]
Thank you. This appears to be a common theme as I'm unable to pull any image successfully. It begins then shuts down shortly after. I'll get with my network team to see if something is up.
