### ISSUE TITLE
How is the  oraclelinux-9-amd64-rootfs.tar.xz built?

### ISSUE THREAD

**Issue by archie-hub** [oracle/container-images#104]
The company I work for doesn't trust docker hub etc etc. They wont trust the tar file in this repo but if I can build it from scratch I might stand half a chance of getting it through.

Do you have any documentation on how the tar.xz was built? They mirror the Oracle repos but I dont see it in there. 

Thanks in advance.

**Comment by tvierling** [comment]
The build process is not documented; it's based on rather complicated build scripts internal to the Oracle Linux build system. Generally you can get a similar result using something like supermin, but that's not something Oracle supports.
