### ISSUE TITLE
Vulnerability scan reports numerous critical issues

### ISSUE THREAD

**Issue by oobles** [oracle/container-images#12]
All of the latest containers have known security vulnerabilities as reported by the Docker scans.  22 components have listed critical vulnerabilities.

https://hub.docker.com/_/oraclelinux/scans/library/oraclelinux/latest

Is there a correct way of mitigating against these issues?  Is there a reason why libraries do not get upgraded and made available?

**Comment by Djelibeybi** [comment]
Those are all false positives from Docker's scanner. If you scan our images with Clair (which uses the published OVAL data from Oracle) you'll see that the images are updated regularly with new RPMs that mitigate any CVEs that have been published.

**Comment by oobles** [comment]
Thanks for the fast response.  It is quite confusing seeing such a big list of vulnerabilities listed and little information searching the web on this.  I'll look into Clair.

**Comment by Djelibeybi** [comment]
> It is quite confusing seeing such a big list of vulnerabilities listed 

Agreed. Docker are aware of the issue and are working with the vendor that provides their scanning software to improve our results, but it appears to be a slow process.
