### ISSUE TITLE
oraclelinux:8-slim is not slim

### ISSUE THREAD

**Issue by riconnon** [oracle/container-images#14]
The oraclelinux:8-slim image is ~4 times the size of oraclelinux:7-slim
```
oraclelinux                                                                              8-slim              8925aeb0d472        17 hours ago        530MB
oraclelinux                                                                              7-slim              d94f4e9e5c13        4 weeks ago         118MB
```
A large part of this seems to come from the inclusion of ~270M of locale data which I would assume is not needed by most docker users by default
```
du -chs usr/lib/locale usr/share/locale
210M    usr/lib/locale
60M     usr/share/locale
269M    total
```
There are also other "databases" included which seem unecessary such as `cracklib`

**Comment by Djelibeybi** [comment]
Thanks for the report. I'll get our build team to look into this.

**Comment by riconnon** [comment]
@Djelibeybi thanks for looking into it. It looks like you could replace `glibc-all-langpacks` with `glibc-langpack-en` to save a whole load of space. Unfortunately `systemd` (which sadly isn't _really_ needed in a docker image) depends on both this and `cracklib` and can't easily be removed.

**Comment by Djelibeybi** [comment]
Yeah, we're going to use the `glibc-minimal-langpack` metapackage which reduces down to UTF8. And you're right about `systemd` but disconnecting and removing that would cause the RPM database to be invalid. It's possibly, but will take a lot more effort.

**Comment by Djelibeybi** [comment]
We've done an initial reduction in size with this commit: https://github.com/oracle/container-images/commit/8e9e64fd5886bd4499e05399372caa7332d71589

We're now reviewing upstream's `ubi-minimal` image and looking to see if we can use `microdnf` as well. We have some use cases that don't seem to work yet, so we may have to do a bit of development on it first.
