### ISSUE TITLE
oraclelinux:6 fails on debian 10

### ISSUE THREAD

**Issue by iwanttobefreak** [oracle/container-images#15]
docker run -ti oraclelinux:6
Fails on debian 10. On debian 9 works.
Thanks

**Comment by Djelibeybi** [comment]
Fails how? What's the error? We'll need way more information.

**Comment by joselegido-avanttic** [comment]
Sorry for giving little information.
Returns prompt and not open the container. I don't know how to debug.
I've seen it happen also with another old versions of debian:
docker run -ti debian:6
docker run -ti debian:7

How can I give you more information?
Thanks

**Comment by Djelibeybi** [comment]
Well, if it happens with older versions of Debian too, this sounds like an issue with Docker on Debian and not something we can fix from the image side.

**Comment by iwanttobefreak** [comment]
I have opened a issue with docker, I don't know if in the right place
https://github.com/docker/for-linux/issues/747

**Comment by Djelibeybi** [comment]
You might want to confirm whether you're runnig Docker CE (from Docker) or a Debian downstrea rebuild. If you're using upstream, that repo seems to be the right place to log an issue.

As this doesn't appear to be an Oracle issue or until proven otherwise, I'm going to close this issue.
