### ISSUE TITLE
oraclelinux:8 /usr/share/zoneinfo doesn't exists

### ISSUE THREAD

**Issue by prosich** [oracle/container-images#19]
tzdata is installed, but /usr/share/zoneinfo doesn't exists.

"dnf reinstall -y tzdata" inside the container creates /usr/share/zoneinfo

**Comment by Djelibeybi** [comment]
Thanks, I'll get the build team to look into why this file is not in the final image.

**Comment by Djelibeybi** [comment]
This has been logged internally as bug 30772559. I'm working through several release blockers for updated 8 and 8-slim images, so this has been added to that stack.

**Comment by Djelibeybi** [comment]
This has been fixed in the latest commit to this repo and has been submitted to the official library via https://github.com/docker-library/official-images/pull/7302
