### ISSUE TITLE
Error pulling image oraclelinux:7.4

### ISSUE THREAD

**Issue by ashokkkannan** [oracle/container-images#2]
Previously we were able to pull oraclelinux:7.4 image, but now the image pull fails with the following error:
`no matching manifest for linux/amd64 in the manifest list entries`.

**Comment by Djelibeybi** [comment]
This was fixed 2 days ago via the following pull request to the official library: https://github.com/docker-library/official-images/pull/4327

**Comment by ashokkkannan** [comment]
But still, the image pull is failing. Do we need to do something on the client-side to make this work ?

**Comment by ashokkkannan** [comment]
oh yeah proxy cache seems to be the probelm. I'm able to pull the image when I'm connected directly.  Thanks for helping me with this issue!
