### ISSUE TITLE
oraclelinux:8 missing libsystemd-shared-239.so

### ISSUE THREAD

**Issue by tkhattra** [oracle/container-images#22]
hello,

libsystemd-shared-239.so seems to be missing from oraclelinux:8 image, so most systemd commands are failing:

```
[root@ce975cbaebf1 /]# systemctl status
systemctl: error while loading shared libraries: libsystemd-shared-239.so: cannot open shared object file: No such file or directory
[root@ce975cbaebf1 bin]# rpm -ql systemd | grep libsystemd
/usr/lib/systemd/libsystemd-shared-239.so
[root@ce975cbaebf1 bin]# ls -l /usr/lib/systemd/libsystemd-shared-239.so
ls: cannot access '/usr/lib/systemd/libsystemd-shared-239.so': No such file or directory
```

thanks
-taj

**Comment by Djelibeybi** [comment]
Thanks, I'll look into this. In the interim, running `dnf reinstall systemd` will fix it.

**Comment by Djelibeybi** [comment]
This issue is resolved via the following PR to the official library: https://github.com/docker-library/official-images/pull/8103

It usually takes between 3-6 hours after merge for the updated images to be available on Docker Hub.
