### ISSUE TITLE
How to install en_US.UTF-8 locale for oraclelinux:7-slim image?

### ISSUE THREAD

**Issue by ethereal-carnival** [oracle/container-images#24]
Couldn't figure it out (no localectl, etc.). Any hint appreciated.

I found an earlier [issue ](https://github.com/oracle/container-images/issues/20)for the same in 8-slim image, but the resolution suggested there (https://github.com/oracle/container-images/issues/20)
is not working on 7-slim. 

![image](https://user-images.githubusercontent.com/25270365/83491961-2fc7d680-a4d0-11ea-9e2f-4f180b15b229.png)

**Comment by Djelibeybi** [comment]
`localectl` is part of `systemd` which is not installed inside the `7-slim` image. However, the `en_US.UTF-8` locale is already installed inside the `oraclelinux:7-slim` image by default. You can check by running `locale -a`.

You may need to set it manually though by exporting `LANG=en_US.UTF-8` in your image.

**Comment by ethereal-carnival** [comment]
This worked, thanks!
