### ISSUE TITLE
Oraclelinux is missing tag latest

### ISSUE THREAD

**Issue by andrewkp101** [oracle/container-images#25]
The latest tag defaults to the latest image.  

It is a standard and offered by all major distributions such as ubuntu
https://registry.hub.docker.com/_/ubuntu?tab=tags

However it is missing here;
https://registry.hub.docker.com/_/oraclelinux/?tab=tags

There is at least one complaint on dockerhub reviews due to this, as when people do a simple default docker command
"docker run oraclelinux"

It doesn't work as this command ultimately defaults to "docker run oraclelinux:latest"

I admit when I did the default command I suspected the distribution was broken, as I am yet to see a Linux distribution that doesn't offer latest.

Could this be fixed please otherwise other people will ultimately find this frustrating and probably end up leaving negative reviews.

**Comment by Djelibeybi** [comment]
This is by design and is documented in the main README.

**Comment by andrewkp101** [comment]
Other Linux versions are not doing this, removing the latest tag causes confusion.

Why break the standard?

It's pretty common sense that if you want to the latest version on the 7 release you should go for the 7 tag and likewise for 8, however if you just want the latest be it 7,8,9,10 just use the latest tag.  This is well understood in the industry.

Going against the standard is never a good thing to do.  The fact that it has only been removed at this very late stage "June 2020" is testimony to this.

Please reopen the issue.

**Comment by Djelibeybi** [comment]
We had many issues when the default changed from 7 to 8. So many issues, that we were forced to revert latest back to 7, which just broke latest. So we removed it completely. That way, you have to make a particular decision which version you want.

**Comment by andrewkp101** [comment]
The logic should be;
If you want version 7, pick the 7 tag
If you want version 8, pick the 8 tag

If you just want the latest and don't care pick the latest tag.  If you are on latest and something is brakes, you go back and work out why which entails going through logs and switching to the 7 tag.  The logs should show that it worked on 7 and stopped working on 8 for example.  This is standard practice.

Maybe 8 was a poor release, I don't know?  In any case having one problem (a poor release?) doesn't provide a good reason to make another problem and going against the docker convention.

People just run "docker run oraclelinux" and when that doesn't work they just think, it's not worth it working out why.  The fact that no other Linux version has done this is something to think about.

**Comment by Djelibeybi** [comment]
I understand the logic, but the way Oracle Linux versions co-exist for years means that it's not that useful in this case.

**Comment by andrewkp101** [comment]
It's not correct, people will just walk away from even trying the product.

**Comment by gotmax23** [comment]
> We had many issues when the default changed from 7 to 8. So many issues, that we were forced to revert latest back to 7, which just broke latest. So we removed it completely. That way, you have to make a particular decision which version you want.

> I understand the logic, but the way Oracle Linux versions co-exist for years means that it's not that useful in this case.

I agree that it is best to pin container images to a specific tag to avoid breakage. This applies to all container images. I don't think that justifies breaking protocol. There are several distributions besides Oracle Linux that have multiple versions (including the other EL distros) and none of them do this.  What issues did you have? I don't understand what is unique about Oracle Linux.

**Screenshot from Docker Hub:**
![2021-08-10_19-31](https://user-images.githubusercontent.com/9920591/128951921-3737196a-eee6-4519-884f-ae4ac9d0fad2.png)
If possible, we should at least fix the prominent instructions that result in an error. If that isn't possible, that goes to show why the `latest` tag should exist.

Thank you for your consideration,
Maxwell

**Comment by Djelibeybi** [comment]
That's totally up to Docker, not us. I encourage you to provide that as feedback here: https://github.com/docker/hub-feedback

**Comment by gotmax23** [comment]
> If possible, we should at least fix the prominent instructions that result in an error

> That's totally up to Docker, not us. I encourage you to provide that as feedback here: https://github.com/docker/hub-feedback

Okay, so it looks like it is not currently possible to fix that. I will consider providing Docker Hub feedback as you suggested.

> We had many issues when the default changed from 7 to 8. So many issues, that we were forced to revert latest back to 7, which just broke latest.

Out of curiosity, what issues did you face?

Thanks.
Maxwell 😀

**Comment by Djelibeybi** [comment]
https://github.com/oracle/container-images/issues/16 was probably the most distruptive.
