### ISSUE TITLE
Naming difference

### ISSUE THREAD

**Issue by senthil13** [oracle/container-images#26]
Why suddenly from Oracle Linux 7.8 is named as 7, not like other images? are you going to follow the same ?

Until 7.7 the image file name is `oraclelinux-7.7-rootfs.tar.xz` but now after 7.8 its `oraclelinux-7-amd64-rootfs.tar.xz` why ?

```
7-slim/oraclelinux-7-slim-amd64-rootfs.tar.xz
7.0/oraclelinux-7.0.tar.xz
7.1/oraclelinux-7.1.tar.xz
7.2/oraclelinux-7.2-rootfs.tar.xz
7.3/oraclelinux-7.3-rootfs.tar.xz
7.4/oraclelinux-7.4-rootfs.tar.xz
7.5/oraclelinux-7.5-rootfs.tar.xz
7.6/oraclelinux-7.6-rootfs.tar.xz
7.7/oraclelinux-7.7-rootfs.tar.xz
7.8/oraclelinux-7-amd64-rootfs.tar.xz

```
same for 8 too

```
8-slim/oraclelinux-8-slim-amd64-rootfs.tar.xz
8.0/oraclelinux-8.0-rootfs.tar.xz
8.1/oraclelinux-8.1-rootfs.tar.xz
8.2/oraclelinux-8-amd64-rootfs.tar.xz
```

**Comment by Djelibeybi** [comment]
Our build teams needed additional clarity in the build artifacts. We are also no longer building the update releases. It's just going to be `oraclelinux:7` and `oraclelinux:8`

**Comment by senthil13** [comment]
Our docker image build pipelines depends on the naming of the file name, In the case of taking the latest build file earlier it have minor version number along with the filename now its having only Major version number which is giving hard time to check which file is what. If the build is going to be without minor version then we can change our pipelines to consider the folder names.

**Comment by Djelibeybi** [comment]
Why are you building from these images instead of using the official ones from Docker Hub or Oracle Container Registry? These tarballs are provided for convenience, but we didn't really expect folks to rebuild from scratch.

**Comment by senthil13** [comment]
We have some customer rpm to apply to meet our security standard. so we are using the tar files, that also will eliminate a additional image layer if we use the docker tar files rather than pulling the images.

**Comment by Djelibeybi** [comment]
That's not a use-case we had considered. Moving forward, we may not maintain the folder strutcture either. It's likely to simplify down to just `7` and `8` with the latest tarball for each of the full and slim variants.

**Comment by senthil13** [comment]
OK, that's fine. I can change the logic to have only 7 or slim, but do you have timeline or ETA when the folder structure changes to 7 or 8 simply ? Also do you published anywhere like release note or change log that the folder name changes?

**Comment by Djelibeybi** [comment]
I don't have an ETA because I don't know if it's been decided yet or not. I don't maintain a changelog of structural repo changes because again, this repo is intended for reference purposes only.
