### ISSUE TITLE
build process

### ISSUE THREAD

**Issue by DougDavenport** [oracle/container-images#29]
Greetings,

Where can we see how these images are built: scripts, kickstart, ...

**Comment by Djelibeybi** [comment]
Excellent question. The scripts we currently use are all based off a modified version of [`moby/mkimage-yum.sh`](https://github.com/moby/moby/blob/master/contrib/mkimage-yum.sh), but we're in the process of refactoring our image build process down to a single script per distro version.

 I'll add an action item to that story to request approval to publish the final refactored scripts on GitHub.

**Comment by vertrost** [comment]
Any updates on this topic?

**Comment by Djelibeybi** [comment]
Not yet. The build team have not yet completed the refactoring effort, as other higher priority tasks took precedence. I'm told now that 8.4 has been released that they should be able to get back to this.

**Comment by Donnix** [comment]
after  i pull the docker pull arm64v8/oraclelinux whats the step next ?

**Comment by Djelibeybi** [comment]
If you're looking for documentation for the container itself, please see https://hub.docker.com/_/oraclelinux

**Comment by Donnix** [comment]
> If you're looking for documentation for the container itself, please see https://hub.docker.com/_/oraclelinux

i dont understand bcs i run on mac m1 chip, can you help me step by step?
