### ISSUE TITLE
After my holuser lab vm applied a kernel patch to 4.1.12-124.48.3.1, because the kernel headers were missing the VM was not functional.

### ISSUE THREAD

**Issue by jhallesy** [oracle/container-images#30]
This VM had the docker feature.  I can't believe this patch was sent out without testing.  It is an obvious error to not include the kernel headers, and I could not find them on the web anywhere.  Fortunately I was able to get my most valuable data off the VM before it went kaput.

**Comment by Djelibeybi** [comment]
I'm not sure exactly which VM you're referring to, or what your issue is, but I'm reasonably sure it has nothing to do with our official Oracle Linux container images, which is what this repo is for. 

I recommend contacting Oracle Support or using the Oracle Virtualisation Community   for further assistance:

https://support.oracle.com/portal/
https://community.oracle.com/tech/

**Comment by jhallesy** [comment]
The issue was not my fault.  A package was missing from the update and
caused data loss. I will drop it because I have no way to know who the
right team is to pass this information on to.  Surely you have some kind of
escalation process you could look into.

John Hallesy

**Comment by Djelibeybi** [comment]
You haven't provided nearly enough information to help, though. You don't specify which HOL VM you're using, nor how you updated, nor how the VM became non-functional or anything that relates to the fact that it may or may not have had Oracle Container Runtime for Docker installed. 

We have lots of escalation processes, but without specific information, it's impossible to know which one. Using either Oracle Support to the Oracle Community is the best way for you to provide the required information to get this properly looked at.

**Comment by jhallesy** [comment]
The name of the VM was DOC-1017486, a test lab for using docker images. The latest kernel patch applied 4.1.12-124.48.3.1, but did not install the kernel header package.  The system runs, but has lost the ability to release the mouse and keyboard to the host.  It can automount a Windows share.  An attempt to install a newer revision of the GuestServices iso failed with "kernel headers not found for target kernel 4.1.12-124.48.3.1.  Install these and retry the install".  A search on the internet for the missing kernel header package yielded zero results.  I guess I will have to wait until there is another major kernel update for a fix, unless someone realizes they goofed and neglected to include the kernel headers for this patch.

**Comment by jhallesy** [comment]
I'll see if I can find a forum for the Oracle community or Oracle support...
