### ISSUE TITLE
Oracle container registry lag

### ISSUE THREAD

**Issue by ripleymj** [oracle/container-images#31]
Sorry if this is the wrong place to ask, but it seemed like the quickest way to reach knowledgeable people. :)

Is there some reason the Oracle Container Registry lags so far behind both Docker Hub and GitHub Container Registry for the oraclelinux:7 image? I'm not sure if its a bug in the upload, or if maybe the README here should mention they get published on a different schedule.

**Comment by Djelibeybi** [comment]
There is currently an issue publishing to OCR that the admin folks are working on, which is preventing us from updating the Oracle Linux images. Once that's resolved, we will push the images ASAP.
