### ISSUE TITLE
Trivy reporting numerous vulnerabilities in oraclelinux:8 (and -slim)

### ISSUE THREAD

**Issue by AntonOellerer** [oracle/container-images#32]
Hey,
When scanning the oraclelinux-8 images with trivy, a number of issues gets reported (as of now 48 for 8, 44 for 8-slim)
Do you know how to solve this?
Best regards,
Anton Oellerer

**Comment by totalamateurhour** [comment]
Can you show some examples of the issues reported?

**Comment by AntonOellerer** [comment]
Hey,
Seems as if the problem has been fixed already, sorry for the troubles.
