### ISSUE TITLE
please upload 8.4 image to the Docker Hub

### ISSUE THREAD

**Issue by Habbie** [oracle/container-images#33]
Hello! If I start an `oraclelinux:8` container and `dnf install cmake`, cmake does not work, because it needs the libarchive version from 8.4, but the image is still 8.3. `dnf upgrade`, of course, fixes that, but it was puzzling me for a while.

Can you please put an 8.4 image on dockerhub? As a nice side effect, this will save users some disk space because `dnf upgrade` doesn't have to fill a layer with all the things that are new in 8.4.

**Comment by totalamateurhour** [comment]
It’s there now.

**Comment by Habbie** [comment]
I see it, thanks!
