### ISSUE TITLE
When will fixes be available for ELSA-2021-9344 ?

### ISSUE THREAD

**Issue by TG-KK** [oracle/container-images#34]

**Comment by tvierling** [comment]
They are fixed by ELSA-2021-9280: glibc-2.28-151.0.1.el8

ELSA-2021-9344 is the version of glibc above *as used with Userspace Ksplice,* a paid add-on to OL.

If you have a scanner tool looking at ELSA-2021-9344, it should actually be looking at ELSA-2021-9280.

**Comment by Djelibeybi** [comment]
I seem to have closed this without pasting the necessary info. Apologies! The image was updated with this fix back in June:https://github.com/oracle/container-images/blob/main/CHANGELOG.md#2021-06-03
