### ISSUE TITLE
Add `latest` tag

### ISSUE THREAD

**Issue by gotmax23** [oracle/container-images#35]
Currently, there is no `latest` tag. Because of this, running `docker|podman pull docker.io/library/oraclelinux` fails. You can work around this issue by specifying a tag (i.e. `docker|podman pull docker.io/library/oraclelinux:8` ). However, I believe the `latest` tag should be added as an alias to the latest available version (currently `8.4`), so this image works like the other images on Docker Hub.

**Screenshot from Docker Hub:**
![2021-08-10_19-31](https://user-images.githubusercontent.com/9920591/128951921-3737196a-eee6-4519-884f-ae4ac9d0fad2.png)
(This doesn't work because there is no latest tag)

**Comment by tvierling** [comment]
This was explained in #25 : https://github.com/oracle/container-images/issues/25#issuecomment-673080644

**Comment by gotmax23** [comment]
I apologize for not doing my due diligence before creating this issue. I will comment on that one instead.
