### ISSUE TITLE
Docker Hub README content for official Oraclelinux image needs updating

### ISSUE THREAD

**Issue by totalamateurhour** [oracle/container-images#36]
https://hub.docker.com/_/oraclelinux lacks content on oraclelinux:8-slim's use of `microdnf` and still mentions Oracle Linux 6 as a supported platform.

**Comment by Djelibeybi** [comment]
Docs updated via https://github.com/docker-library/docs/pull/2079 and Oracle Linux 6 removed via https://github.com/docker-library/official-images/pull/11310.
