### ISSUE TITLE
Oracle linux 6.10, Docker port mapping fails 

### ISSUE THREAD

**Issue by melias77** [oracle/container-images#4]
Hi,
Im strugling with weblogic 12.2.1.3 server on docker. I cant do "- p 8001:7001" with docker run. Do u anyone know how to make oracle linux image ready for port mapping or is there a dedicated one with no firewall etc. Can anyone tell me what to disable to make port mapping work with docker and oracle linux image?
Kind 
Regards
Elias

**Comment by Djelibeybi** [comment]
This repo is for the Oracle Linux base images only. If you're having an issue with the WebLogic image, please open an issue in the https://github.com/oracle/docker-images repo.
