### ISSUE TITLE
Fix docker pull information on the Docker Hub

### ISSUE THREAD

**Issue by kral2** [oracle/container-images#43]
The Docker Hub page for Oracle Linux guides the user to issue this command: `docker pull oraclelinux` without any tag. This is interpreted by docker cli as using the `latest` tag, which does not exist as mentioned lower in the README.
![screenshot 2022-03-28 at 15 16 38](https://user-images.githubusercontent.com/6201562/160406059-6d8c968a-cfcf-4736-9716-85769f44bcf5.png)

Yet, when using the suggested command, the user gets the error output below:
```Shell
❯ docker pull oraclelinux
Using default tag: latest
Error response from daemon: manifest for oraclelinux:latest not found: manifest unknown: manifest unknown
```

It would be a better user experience if the first command a user execute do not fail. I would prefer to get an opinionated suggestion to use `oraclelinux:8` for example and look at existing tags later if this doesn't work for my particular requirements, rather than having to enter troubleshooting mode right at the beginning.

**Comment by Djelibeybi** [comment]
Unfortunately not: that line is auto-generated by Docker Hub and multiple requests to fix or even suppress it have not yielded any results. We do call out the fact that there is no latest tag in the actual docs on that page, though we should probably make that a bit more obvious.

I'll tinker with the docs and submit something accordingly.

**Comment by Djelibeybi** [comment]
I've submitted https://github.com/docker-library/docs/pull/2166 to the docs repo
