### ISSUE TITLE
stable tags of slim variants not available

### ISSUE THREAD

**Issue by fredcooke** [oracle/container-images#49]
7-slim etc are constantly rewritten - there are no 7.7-slim versions with venerable ages like there are for the plain 7.7 etc variants that go right back and are untouched - this means we cannot get a stable build without producing in house 7-slim-DATE tags many of which will be identical to each other since we can't know when a new one comes except through manual inspection.

Similarly the Dockerfile has no history, just a single commit 8 days ago in line with the timing of the tags themselves. I speculate that you're committing binaries to the repo and want to keep it slim-ish by force pushing on the regular or something? Not a pleasant architecture to consume or work with overall.

**Comment by tvierling** [comment]
On that note: If you want a stable base tag, you are free to pull a tag and retag it in-house for reproducibility purposes. There's nothing stopping you from doing, for instance,

docker|podman pull ghcr.io/oracle/oraclelinux:7-slim
docker|podman tag ghcr.io/oracle/oraclelinux:7-slim my-oraclelinux:7-slim-$(date +%Y%m%d)

whenever you want to get a new "stable base image". This is a recommended way to do exactly this sort of thing with any external Docker image you use.
