### ISSUE TITLE
Yum commands fail

### ISSUE THREAD

**Issue by danieltura** [oracle/container-images#52]
Any yum install <pkg> and yum update command fail with the following error:
```
Errors during downloading metadata for repository 'ol9_baseos_latest':
  - Curl error (6): Couldn't resolve host name for https://yum.oracle.com/repo/OracleLinux/OL9/baseos/latest/repodata/repomd.xml [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'ol9_baseos_latest': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

**Comment by tvierling** [comment]
This indicates that your container networking is not working correctly; the `oraclelinux:9[-slim]` images work just fine for me.

What is the host system, and what container runtime (docker, podman, etc.) are you using?
