### ISSUE TITLE
where can i download oraclelinux-9-amd64-rootfs.tar.xz

### ISSUE THREAD

**Issue by caffcabe** [oracle/container-images#56]
when i want to create oracle docker container,the docker file is 
FROM scratch

ADD oraclelinux-9-amd64-rootfs.tar.xz /

# overwrite this with 'CMD []' in a dependent Dockerfile
CMD ["/bin/bash"]

now I need download oraclelinux-9-amd64-rootfs.tar.xz file

**Comment by amsteinb-orcl** [comment]
It is in the dist-amd64 branch of this repo:

https://github.com/oracle/container-images/blob/dist-amd64/9/oraclelinux-9-amd64-rootfs.tar.xz

**Comment by amsteinb-orcl** [comment]
I will assume my comment was sufficient to resolve this issue.
