### ISSUE TITLE
README refers to microdnf and slim images

### ISSUE THREAD

**Issue by asgeirn** [oracle/container-images#59]
Ref. oracle/docker-images#2020 the use of the `8-slim` base image and `microdnf` has been deprecated.

Readme should be updated to reflect this change.

**Comment by tvierling** [comment]
The slim images, and microdnf, are still supported in the Oracle Linux base images.

The link you referred to is talking about the Oracle Linux *developer images,* which are images containing additional tools on top of the base images. They were transitioned to use the non-slim image.
