### ISSUE TITLE
slim-7 image broken

### ISSUE THREAD

**Issue by jaydee18** [oracle/container-images#6]
Receiving this message when trying to pull oraclelinux:7-slim

Error response from daemon: manifest for oraclelinux:slim-7 not found

**Comment by Djelibeybi** [comment]
Works fine for me:

```
$ docker pull oraclelinux:7-slim
Trying to pull repository docker.io/oraclelinux ...
7-slim: Pulling from docker.io/library/oraclelinux
f25d82609194: Pull complete
Digest: sha256:2ed2820810409491b0d8fced14b5f6b3fd8206eb8fbf5f9138d825c5a98db020
Status: Downloaded newer image for oraclelinux:7-slim
```

Please double-check that you're using `oraclelinux:7-slim` in the pull comannd as your error message says `slim-7` which is incorrect.

**Comment by jaydee18** [comment]
Ah ... sorry ... that was a typo ... I'm getting this when running my Dockerfile:

$ docker build --tag="mymod/httpd:v2" .
Sending build context to Docker daemon   5.12kB
Step 1/7 : FROM oraclelinux:7-slim
 ---> b19454a5f17a
Step 2/7 : MAINTAINER A N Other <another@example.com>
 ---> Running in 85e4f8e2f358
Removing intermediate container 85e4f8e2f358
 ---> 78ca6714d113
Step 3/7 : RUN sed -i -e '/^\[main\]/aproxy=http://proxy.example.com:80' /etc/yum.conf
 ---> Running in de4aa0a6caef
Removing intermediate container de4aa0a6caef
 ---> 610f6ce9f838
Step 4/7 : RUN yum -y install httpd
 ---> Running in 6aa14d768cfc
Loaded plugins: ovl
https://yum.oracle.com/repo/OracleLinux/OL7/UEKR4/x86_64/repodata/repomd.xml: [Errno 14] curl#5 - "Could not resolve proxy: proxy.example.com; Name or service not known"
Trying other mirror.

One of the configured repositories failed (Latest Unbreakable Enterprise Kernel Release 4 for Oracle Linux 7Server (x86_64)),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=ol7_UEKR4 ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable ol7_UEKR4
        or
            subscription-manager repos --disable=ol7_UEKR4

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=ol7_UEKR4.skip_if_unavailable=true

failure: repodata/repomd.xml from ol7_UEKR4: [Errno 256] No more mirrors to try.
https://yum.oracle.com/repo/OracleLinux/OL7/UEKR4/x86_64/repodata/repomd.xml: [Errno 14] curl#5 - "Could not resolve proxy: proxy.example.com; Name or service not known"
The command '/bin/sh -c yum -y install httpd' returned a non-zero code: 1

**Comment by Djelibeybi** [comment]
You're getting a failure resolving the address of `proxy.example.com`. Again, this has nothing to do with the Oracle Linux base image. You need to make sure you use the right address that the Docker container can resolve and connect to.

I am closing this issue now. If you have further issues with containers created using Oracle Linux, please open another issue in our Docker images repo: https://github.com/oracle/docker-images
