### ISSUE TITLE
Why doesn't the official oraclelinx have any software, it doesn't even seem to have oracle installed, what's the point,

### ISSUE THREAD

**Issue by mikeside** [oracle/container-images#63]
Why doesn't the official oraclelinx have any software, it doesn't even seem to have oracle installed, what's the point,

**Comment by totalamateurhour** [comment]
This repo is purely to store rootfs tarballs used to create Oracle Linux base images. If you are interested building container images with various (commercial) Oracle products, check out this repository: https://github.com/oracle/docker-images

**Comment by mikeside** [comment]
Is there an oracle package for mac m1? I can't seem to find the oracle package for m1
from 阿里邮箱 macOS------------------------------------------------------------------
发件人：Sergio ***@***.***>
日　期：2023年12月13日 15:59:35
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [oracle/container-images] Why doesn't the official oraclelinx have any software, it doesn't even seem to have oracle installed, what's the point, (Issue #63)

This repo is purely to store rootfs tarballs used to create Oracle Linux base images. If you are interested building container images with various (commercial) Oracle products, check out this repository: https://github.com/oracle/docker-images
