### ISSUE TITLE
Oraclelinux:8 container with port mapping failure

### ISSUE THREAD

**Issue by omalisson** [oracle/container-images#66]
Hello!

I'm running an oraclelinux:8 container to run an elastic-agent (installation successful) where ports 8200 and 8220 were mapped for communication with the APM service.
The ports were mapped in iptables correctly and the traffic from the APM server reaches the host, however the response received is "Connection refused" and when testing the respective ports the result shows "port closed".

Below is some information:

# Output of the "docker ps" command:
Image: oraclelinux:8
Command: "/bin/bash"
Ports: 0.0.0.0:8200->8200/tcp
        :::8200->8200/tcp
        0.0.0.0:8220->8220/tcp
        :::8220->8220/tcp

# iptables output:

ChainDOCKER (2 references)
num target prot opt source destination
1 ACCEPT tcp -- 0.0.0.0/0 172.18.0.2 tcp dpt:9200
2 ACCEPT tcp -- 0.0.0.0/0 172.18.0.3 tcp dpt:5601
3 ACCEPT tcp -- 0.0.0.0/0 172.18.0.4 tcp dpt:8220
4 ACCEPT tcp -- 0.0.0.0/0 172.18.0.4 tcp dpt:8200

If anyone can help me solve this problem I would be very grateful!

**Comment by tvierling** [comment]
If you are an Oracle Linux or OCI customer, please open a support ticket for product support (the Github issue tracker is not a product support venue).
