### ISSUE TITLE
Missing X-slim-latest tag

### ISSUE THREAD

**Issue by FrankBurmo** [oracle/container-images#7]
I think the tagging of the slim-images should be done in another way.

The way it is set up today, it is not possible to pull a previous version 7 slim-image, for instance version 7.5-slim. It is just **7-slim**, which is actually just a slim latest version. 

It should be this way:
**7-slim-latest** (the latest version in slim-form, what is tagged as **7-slim** today)
**7.5-slim**
**7.4-slim**
etc.

Read about Docker and the :latest anti-pattern here: http://blog.benhall.me.uk/2015/01/dockerfile-latest-tag-anti-pattern/

**Comment by tvierling** [comment]
Honestly, if you think you have a use case for `7.5-slim`, then you are doing something wrong.

OS images are not static lines in the sand. You can start with a given image, but if you are not doing something like a `docker exec ... yum update -y` cron job on a regular basis, even your containers will become vulnerable to security bugs. These are miniature operating system images, after all, and there is *no valid use case* for intentionally using a not-up-to-date patchlevel of such an image.

I strongly recommend rejecting this proposal.

**Comment by Djelibeybi** [comment]
Thanks for that fantastic explanation, Todd. As such, I am closing this issue because there is no further discussion to be had.

**Comment by tvierling** [comment]
The *version* of the operating system is *OL7*, full stop. The number after the dot is NOT PART of the product version; it is only an indicator of *minimum patchlevel* of component RPMs.

Oracle Linux Support is on the hook to guarantee patch compatibility with previous RPM patches in the same version (OL7).

Not updating packages, thus intentionally opening up a system to known (and already fixed) security vulnerabilities, makes the use case of using an older patchlevel invalid. No vendor should be allowed to prevent security patching.
