### ISSUE TITLE
yum introduces broken repo when used in OCI

### ISSUE THREAD

**Issue by chendelb** [oracle/container-images#9]
Using the oraclelinux:7-slim (93c6055c3338) image in OCI (Oracle Cloud) and calling `yum update -y` twice results in a 404 error:
`http://yum.oracle.com/repo/OracleLinux/OL7/oci/included/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found` 
After updating the first time there is an enabled `ol7_ociyum_config` repo that points to a non-existent URL which causes the subsequent `yum update` to fail. 
This only occurs inside OCI. 
To reproduce:
- Create VM in OCI and install docker-engine
- `docker run -it --rm --name foobar oraclelinux:7-slim /bin/bash`
- call `yum update -y` twice

**Comment by Djelibeybi** [comment]
Is this still an issue with the latest `oraclelinux:7-slim` image?

**Comment by chendelb** [comment]
Checked.
Issue fixed in sha256:76f330ae2797bcce363c5267da3b3d49377397fe7c01fc0c1ee13fe86fec185a
